import = [
  "~/.config/alacritty/themes/nordfox.toml"
]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = 11.5

[font.bold]
style = "Regular"

[font.bold_italic]
style = "Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font Mono"
style = "Regular"

[bell]
color = "#cdcecf"
animation = "EaseOut"
duration = 100

[window]
decorations = "None"
padding = { x = 2, y = 1 }
dynamic_padding = true
