# GNU and BSD (macOS) ls use different flags
if $(ls --version &>/dev/null); then
    lsflags="--color=auto --group-directories-first"
else
    lsflags="-G"
    export CLICOLOR=1
fi

# Use Solarized palette for commands that support dircolors
# TODO nix install 'dircolors-solarized'
if (( $+commands[dircolors] )); then
    test -r "$HOME/.dircolors" && eval "$(dircolors $HOME/.dircolors)" || eval "$(dircolors -b)"

    # Colorify other things
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Aliases
alias ls="ls ${lsflags}"        # use color
alias ll="ls ${lsflags} -lh"    # show human readable sizes
alias la="ls ${lsflags} -lhA"   # show all files (except . and ..)
alias lt="ls ${lsflags} -lhtr"  # show by date modified (oldest first)
alias l="ll"                    # pacify the monster

# More suitable for .zshenv
EDITOR=emacs

# History settings
HISTFILE="${HOME}/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt append_history              # allow multiple sessions to append to one history
setopt bang_hist                   # treat ! special during command expansion
setopt extended_history            # Write history in :start:elasped;command format
setopt hist_expire_dups_first      # expire duplicates first when trimming history
setopt hist_find_no_dups           # When searching history, don't repeat
setopt hist_ignore_dups            # ignore duplicate entries of previous events
setopt hist_ignore_space           # prefix command with a space to skip it's recording
setopt hist_reduce_blanks          # Remove extra blanks from each command added to history
setopt hist_verify                 # Don't execute immediately upon history expansion
setopt inc_append_history          # Write to history file immediately, not when shell quits
setopt share_history               # Share history among all sessions

# Tab completion
autoload -Uz compinit && compinit
setopt complete_in_word            # cd /ho/sco/tm<TAB> expands to /home/scott/tmp
setopt auto_menu                   # show completion menu on succesive tab presses
setopt autocd                      # cd to a folder just by typing it's name
ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;&' # These "eat" the auto prior space after a tab complete

# Misc
setopt interactive_comments        # allow # comments in shell; good for copy/paste
unsetopt correct_all               # I don't care for 'suggestions' from ZSH
export BLOCK_SIZE="'1"             # Add commas to file sizes

# Path
typeset -gU path                   # keep duplicates out of the path

# Bindkey
bindkey -e
bindkey '\e[3~' delete-char
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey ' '  magic-space

#
