gui:
  nerdFontsVersion: "3"
git:
  branchLogCmd: "git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editPreset: "nvim-remote"
